repos:
    - repo: https://github.com/ambv/black
      rev: 22.6.0
      hooks:
        - id: black
          language: python
          types: [python]
          args: ["--line-length=100"]
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: ["--filter-files", "--profile", "black"]
        files: \.py$