import cvxpy as cp
from typing import Any, Dict, List, Tuple

SampleAdjacency = Dict[Tuple[str,str], int]

root_node_name: str

class SampleNode:
  # Properties generated by C++
  name: str
  x: int
  y: int
  downstream_node: str
  upstream_nodes: List[str]
  area: int
  total_upstream_area: int
  # Properties added dynamically by Python
  my_value: Any # TODO: cp.Variable
  my_flux: Any # TODO: cp.Expression?
  total_flux: Any # TODO: cp.Expression?
  label: int

def fastunmix(data_dir: str) -> Tuple[Dict[str, SampleNode], SampleAdjacency]: ...
